FROM ubuntu:18.04
MAINTAINER Pete Zybrick <pzybrick@gmail.com>

RUN apt-get update \
 && apt-get -yqq install nano ssh \
 && apt-get install -y curl unzip \
 && apt-get install -y  \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*    
 
# JAVA
ARG JAVA_MAJOR_VERSION=8
ARG JAVA_UPDATE_VERSION=172
ENV JAVA_HOME /usr/jdk1.${JAVA_MAJOR_VERSION}.0_${JAVA_UPDATE_VERSION}
ENV PATH $PATH:$JAVA_HOME/bin
add server-jre-${JAVA_MAJOR_VERSION}u${JAVA_UPDATE_VERSION}-linux-x64.tar.gz /usr
RUN  ln -s $JAVA_HOME /usr/java \
  && rm -rf $JAVA_HOME/man \
  && rm -rf server-jre-${JAVA_MAJOR_VERSION}u${JAVA_UPDATE_VERSION}-linux-x64.tar.gz

# http://blog.stuart.axelbrooke.com/python-3-on-spark-return-of-the-pythonhashseed
ENV PYTHONHASHSEED 0
ENV PYTHONIOENCODING UTF-8
ENV PIP_DISABLE_PIP_VERSION_CHECK 1