version: '3'

services:
  pipeline-spark-master:
    image: spark:2.4.0
    command: bin/spark-class org.apache.spark.deploy.master.Master -h pipeline-spark-master
    hostname: pipeline-spark-master
    container_name: pipeline-spark-master
    environment:
      MASTER: spark://pipeline-spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 8g
      SPARK_DRIVER_MEMORY: 8G
      SPARK_DAEMON_MEMORY: 8G
    expose:
    - 465
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - sudo
    - 6066
    ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
    volumes:
    - ./shared:/tmp/shared
    - ./spark/conf/master:/conf

  pipeline-spark-worker1:
    image: spark:2.4.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://pipeline-spark-master:7077
    hostname: pipeline-spark-worker1
    container_name: pipeline-spark-worker1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 8g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8181
      SPARK_PUBLIC_DNS: localhost
      SPARK_EXECUTOR_INSTANCES: 2
      SPARK_EXECUTOR_CORES: 2
      SPARK_EXECUTOR_MEMORY: 8G
      SPARK_DRIVER_MEMORY: 8G
      SPARK_DAEMON_MEMORY: 8G
    links:
    - pipeline-spark-master
    expose:
    - 465
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
    ports:
    - 8181:8181
    volumes:
    - ./shared:/tmp/shared
    - ./spark/conf/worker:/conf

  pipeline-spark-worker2:
    image: spark:2.4.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://pipeline-spark-master:7077
    hostname: pipeline-spark-worker2
    container_name: pipeline-spark-worker2
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 8g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8182
      SPARK_PUBLIC_DNS: localhost
      SPARK_EXECUTOR_INSTANCES: 2
      SPARK_EXECUTOR_CORES: 2
      SPARK_EXECUTOR_MEMORY: 8G
      SPARK_DRIVER_MEMORY: 8G
      SPARK_DAEMON_MEMORY: 8G
    links:
    - pipeline-spark-master
    expose:
    - 465
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
    ports:
    - 8182:8182
    volumes:
    - ./shared:/tmp/shared
    - ./spark/conf/worker:/conf

  pipeline-spark-worker3:
    image: spark:2.4.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://pipeline-spark-master:7077
    hostname: pipeline-spark-worker3
    container_name: pipeline-spark-worker3
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 8g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8183
      SPARK_PUBLIC_DNS: localhost
      SPARK_EXECUTOR_INSTANCES: 2
      SPARK_EXECUTOR_CORES: 2
      SPARK_EXECUTOR_MEMORY: 8G
      SPARK_DRIVER_MEMORY: 8G
      SPARK_DAEMON_MEMORY: 8G
    links:
    - pipeline-spark-master
    expose:
    - 465
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
    ports:
    - 8183:8183
    volumes:
    - ./shared:/tmp/shared
    - ./spark/conf/worker:/conf

  pipeline-spark-worker4:
    image: spark:2.4.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://pipeline-spark-master:7077
    hostname: pipeline-spark-worker4
    container_name: pipeline-spark-worker4
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 8g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8184
      SPARK_PUBLIC_DNS: localhost
      SPARK_EXECUTOR_INSTANCES: 2
      SPARK_EXECUTOR_CORES: 2
      SPARK_EXECUTOR_MEMORY: 8G
      SPARK_DRIVER_MEMORY: 8G
      SPARK_DAEMON_MEMORY: 8G
    links:
    - pipeline-spark-master
    expose:
    - 465
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
    ports:
    - 8184:8184
    volumes:
    - ./shared:/tmp/shared
    - ./spark/conf/worker:/conf

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.3-java8
    container_name: namenode
    ports:
      - 9870:9870
      - 9000:9000
    expose:
      - 9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./shared:/tmp/shared
      - ~/.aws:/root/.aws
    environment:
      CLUSTER_NAME: test
      HADOOP_PREFIX: "/opt/hadoop-3.2.1"
    env_file:
      - ./hadoop/hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.3-java8
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - ./shared:/tmp/shared
      - ~/.aws:/root/.aws
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      HADOOP_PREFIX: "/opt/hadoop-3.2.1"
    env_file:
      - ./hadoop/hadoop.env

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.1.3-java8
    container_name: resourcemanager
    volumes:
      - ./shared:/tmp/shared
      - ~/.aws:/root/.aws
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
      HADOOP_PREFIX: "/opt/hadoop-3.2.1"
    env_file:
      - ./hadoop/hadoop.env

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.1.3-java8
    container_name: nodemanager
    volumes:
      - ./shared:/tmp/shared
      - ~/.aws:/root/.aws
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
      HADOOP_PREFIX: "/opt/hadoop-3.2.1"
    env_file:
      - ./hadoop/hadoop.env

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.1.3-java8
    container_name: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
      HADOOP_PREFIX: "/opt/hadoop-3.2.1"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
      - ./shared:/tmp/shared
      - ~/.aws:/root/.aws
    env_file:
      - ./hadoop/hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
